config/routes.rb
Rails.application.routes.draw do
  mount API::Base, at: "/"
  resources :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  extend LeanTag::Taggable
  taggable_on :tags

  validates_inclusion_of :sell_status, :in => %w(Sellable Reject)

  serialize :images, JSON
  mount_uploaders :images, ImageUploader
end

app/controllers/api/base.rb
module API
  class Base < Grape::API
    mount API::V1::Base
  end
end

app/controllers/api/v1/base.rb
module API
  module V1
    class Base < Grape::API
      mount API::V1::Products
    end
  end
end

app/controllers/api/v1/defaults.rb
module API
  module V1
    module Defaults
      extend ActiveSupport::Concern

      included do
        prefix "api"
        version "v1", using: :path
        default_format :json
        format :json

        helpers do
          def permitted_params
            @permitted_params ||= declared(params,
               include_missing: false)
          end

          def logger
            Rails.logger
          end
        end

        rescue_from ActiveRecord::RecordNotFound do |e|
          error_response(message: e.message, status: 404)
        end

        rescue_from ActiveRecord::RecordInvalid do |e|
          error_response(message: e.message, status: 422)
        end
      end
    end
  end
end

app/controllers/api/v1/products.rb
module API
  module V1
    class Products < Grape::API
      include API::V1::Defaults

      resource :products do
        desc "Return all products"
        get "", root: :products do
          data = []
          Product.all.each do |p|
            result = {
              response: "Successful",
              data: {
                id: p.id,
                uuid: p.uuid,
                images: p.images_urls,
                tags: p.tag_list.split(","),
                sell_status: p.sell_status,
                created: p.created_at,
                updated: p.updated_at
              }
            }
            data << result
          end
          return data
        end

        desc "Return a product"
        params do
          requires :uuid, type: String, desc: "UUID of the
            product"
        end
        get ":uuid", root: "product" do

          result = Product.find_by(uuid: permitted_params[:uuid])

          if !result.nil?
            data = {
              response: "Successful",
              data: {
                id: result.id,
                uuid: result.uuid,
                images: result.images_urls,
                tags: result.tag_list.split(","),
                sell_status: result.sell_status,
                created: result.created_at,
                updated: result.updated_at
              }
            }
          else
            data = {
              response: "Error",
              data: result
            }
          end

          return data
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    # raise params["product"][:images].inspect
    @product = Product.new(product_params)
    @product.uuid = SecureRandom.hex
    if @product.save
      @product.tag_list = params["product"][:tag_list]
      if @product.save
        redirect_to product_path(@product)
      end
    else
      redirect_to new_product_path()
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      @product.tag_list = params["product"][:tag_list].join(",")
      if @product.save
        redirect_to product_path(@product)
      end
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_path
    end
  end

  private
  def product_params
    params.require(:product).permit(:sell_status, { images: [] })
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VinikuraDistributionSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<div class="container">
  <%= form_for @product do |p| %>
    <div class="form-group">
      <%= p.label "upload product image" %>
      <%= p.file_field :image, class: "form-control-file" %>
    </div>
    <div class="form-group">
      <%= p.label "add tag" %>
      <%= p.text_field :tag_list, multiple: true, class: "form-control" %>
    </div>
    <%= p.submit %>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="btn btn-secondary">
    <%= link_to "New Product", new_product_path %>
  </div>
  <table class="table">
    <thead class="table">
      <tr class="row">
        <td>#</td>
        <td>Images</td>
        <td>Tags</td>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
      <tr id="<%= product.id %>" class="row">
        <td><%= product.uuid %></td>
        <td><%= image_tag product.images[0].thumb.url, :size=> "300x300" %></td>
        <td><%= product.tag_list %></td>
        <td><%= link_to "Show", product_path(product) %></td>
        <td><%= link_to "Edit", edit_product_path(product) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<div class="container">
  <%= form_for @product, :html => { :multipart => true }  do |p| %>
    <div class="form-group">
      <%= p.label "Upload Product Image" %>
      <%= p.file_field :images, multiple: true, class: "form-control-file" %>
    </div>
    <div class="form-group">
      <%= p.label "Add Tag" %>
      <%= p.text_field :tag_list, class: "form-control" %>
    </div>

    <div class="btn-group" data-toggle="buttons-radio">
      <%= p.label "Sellable" %>
      <%= p.radio_button :sell_status, "Sellable", checked: "checked" %>

      <%= p.label "Reject" %>
      <%= p.radio_button :sell_status, "Reject"%>
    </div>
    <div>
      <%= p.submit %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="container">
  <div id="<%= @product.id %>">
  <div id="product-image">
  <% @product.images.each do |img| %>
    <%= image_tag img.thumb.url %>
  <% end %>
  </div>
  <div id="product-list">
    <% @product.tag_list.split(",").each do |tag| %>
      <div>
        <%= tag %>
      </div>
    <% end %>
  </div>
  <%= link_to "Continue Adding New Product", new_product_path %>
</div>